### ISSUE TITLE
During cmake instructions when installing raisimOgre

### ISSUE THREAD

**Issue by AdamWSL** [raisimTech/raisimOgre#10]
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a package configuration file provided by "raisim" (requested
  version 0.6.0) with any of the following names:

    raisimConfig.cmake
    raisim-config.cmake

  Add the installation prefix of "raisim" to CMAKE_PREFIX_PATH or set
  "raisim_DIR" to a directory containing one of the above files.  If "raisim"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by AdamWSL** [comment]
I have installed raisim in other repository,

**Comment by jhwangbo** [comment]
the error message already answers it. You have to add raisim directory to the ``CMAKE_PREFIX_PATH``. The install instruction says

```
cd $WORKSPACE
cd raisimOgre && mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$LOCAL_INSTALL -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DRAISIM_OGRE_EXAMPLES=ON
make install -j8
```
If you copy-pasted this, this means that you didn't add $LOCAL_INSTALL to your environment variable

**Comment by AdamWSL** [comment]
thanks!I GET it!
