### ISSUE TITLE
Height map is not visualized correctly

### ISSUE THREAD

**Issue by mktk1117** [raisimTech/raisimOgre#14]
From `3a77c7c71c11348ecdcb5b73dc42a5549c6184b2`,
the height map is not visualized correctly.

**Comment by jhwangbo** [comment]
it all works fine for me. Are you using the latest version of RaiSim?

**Comment by mktk1117** [comment]
Yes, I'm using the newest version of raisimLib.
It seems that when the heightmap is updated, it still keeps the old map and does not update it.

**Comment by jhwangbo** [comment]
I guess the issue happened here ``0a5052fd090e85f725c448a1877c3b286369bbef``. I fixed it and pushed the change
