### ISSUE TITLE
Finding an old repository

### ISSUE THREAD

**Issue by MusubaPy** [raisimTech/raisimOgre#17]
Hello, Jemin

1. I am trying to find your old repository. I am interested in the file where there is this simulation:
https://raisim.com/_images/raisimGymTorch_trainedPolicy2.gif

2. Where can I find information on connecting RaiSim and ROS? Or information on importing data to a real robot?

Thanks in advance!

**Comment by jhwangbo** [comment]
1. that is unpublished work. will be published soon
2. RaiSim is a C++ library. It is somewhat trivial to use it in a ROS package. If you want to use a trained policy on the robot, you just copy-paste the .pt file and use libpytorch.
