### ISSUE TITLE
LOCAL_BUILD parameter should be changed to LOCAL_INSTALL

### ISSUE THREAD

**Issue by jeeseop** [raisimTech/raisimOgre#2]
Currently, raisimOgre moves under raisimTech group which uses LOCAL_INSTALL as a new directory name in raisimLib.
So, LOCAL_BUILD paramete names also should be changed to LOCAL_INSTALL

**Comment by jhwangbo** [comment]
Hi Jeeseop, I guess you meant the README.md file. I fixed it and pushed the commit

**Comment by jeeseop** [comment]
Oops, sorry for short description.
Yes, that's what I wanted to mention.
Thanks for the update.
