### ISSUE TITLE
Possibility of rendering one ogre visualization frame in different threat or loop

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimOgre#24]
Hi Raisim Tech,

recently I was subscribing the joint angles of the quadruped from a ros topic and then use them as PdTarget for the Raisim. From that topic I can not only read the ros::time but also joint angles of the robot. I used the setPdTarget in a while loop like this:

```
while (ros::ok()){
world.setTimeStep((raisim_PD.timeStamp - lastTimeStampt).toSec());
lastTimeStampt = raisim_PD.timeStamp;

// prepares all kinematic and dynamic quantities for the current time step
world.integrate1(); 

jointsPTarget << 0, 0, 0, 0, 0, 0, 0, 
                 raisim_PD.joints[0], raisim_PD.joints[1], raisim_PD.joints[2], 
                 raisim_PD.joints[6], raisim_PD.joints[7], raisim_PD.joints[8], 
                 raisim_PD.joints[3], raisim_PD.joints[4], raisim_PD.joints[5], 
                 raisim_PD.joints[9], raisim_PD.joints[10], raisim_PD.joints[11];

anymal.back()->setPdTarget(jointsPTarget, jointVelocityTarget);

// actually move time foward and change the state
world.integrate2();

vis->renderOneFrame();
ros::spinOnce();
}
```

I realized that the "vis->renderOneFrame();" took more time than my subscription frequency so that my whole PD controller target setting frequency for Raisim was also reduced. I was wondering can I also run the renderOneFrame command in a separate loop so that it won't reduce my controller's frequency?

Thank you in advance.

Best

**Comment by jhwangbo** [comment]
Yes, you can use a separate thread. But make sure that everything related to raisimOgre should be in the same thread. Opengl API's cannot be called in multiple threads

**Comment by edward9503** [comment]
> raisimOgre

Thanks for the reply!
