### ISSUE TITLE
Stereo camera possible?

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimOgre#25]
Dear RaiSim Team,

As discussed in #23, it is impossible to render two different images for the simulation. But I wonder if it is possible to add a stereo camera view for the simulator? Because we are gonna obtain a stereo camera view from RaiSim and use it to get the depth info. Thanks for any feedback.

Best

**Comment by edward9503** [comment]
Hi,

any feedback on this? @jhwangbo 

Thank you so much for any feedback.

Best

**Comment by jhwangbo** [comment]
sorry for the late response. No, it does not support the stereo vision.
You can try rayTest to get depth information if that's what you want.
