### ISSUE TITLE
Unknown argument -OGRE_BUILD_COMPONENT_JAVA=OFF

### ISSUE THREAD

**Issue by BiligeYang** [raisimTech/raisimOgre#27]
When I was installing Ogre by running:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DOGRE_BUILD_COMPONENT_BITES=ON -OGRE_BUILD_COMPONENT_JAVA=OFF -DOGRE_BUILD_DEPENDENCIES=OFF -DOGRE_BUILD_SAMPLES=False`

Cmake gave an error "Unknown argument -OGRE_BUILD_COMPONENT_JAVA=OFF". After I just deleted this argument, it seemed to work. Any reason why? 

I am on Ubuntu 16.04.

**Comment by jhwangbo** [comment]
This argument was used in the older Ogre version and it is no longer needed. I'll update the instruction.
