### ISSUE TITLE
PCRE SWIG problem solved 

### ISSUE THREAD

**Issue by Lr-2002** [raisimTech/raisimOgre#28]
# Problem desicription
```
OS: ubunut 20.04
CPU: AMD R7 4700H
GPU: RTX 2060
g++: version is  9.0
```
## Problem
```
swig:7: error: pcre regex matching is not available in this swig build.
```
this problem happened when run`make install  -j4` after the  `cmake`

# Solution
using `g++-8` rather than `g++-9`

**Comment by jhwangbo** [comment]
Thx for posting. I recommend using raisimUnity and raisimUnreal if possible because they are better supported

**Comment by Lr-2002** [comment]
yep, to be honest , unity is much easier to use 
however, there is a powerful research using your lib

**Comment by Lr-2002** [comment]
what's more, some other bugs happend

one was the ogre compilation.
there was always `java` compiling while it seems have no function.
so 
go to `cmakelist.txt` of ogre, and change the compilation of java to `FALSE` and i'll help

**Comment by jhwangbo** [comment]
I meant raisimUnity. You can use raisimUnity to visualize a raisim environment. There are a few examples in the repo
