### ISSUE TITLE
Unable to make the ogre (and hence raisimOgre) in Ubuntu 22.04

### ISSUE THREAD

**Issue by ruturajsambhusvt** [raisimTech/raisimOgre#29]
Hello, 

I have been trying hard to install raisimOgre but ogre "make" throws errors. While I have seen the previous issue where it is suggested to use RaisimUnity, I must use RaisimOgre since all the work in my research group is based on it. I am attaching herewith the console output of the `make install -j8`  command for Ogre. I request your assistance!

[ogre_make_errors.txt](https://github.com/raisimTech/raisimOgre/files/12901042/ogre_make_errors.txt)

**Comment by jhwangbo** [comment]
Can you build ogre with ``OGRE_BUILD_COMPONENT_JAVA=OFF``? I also modified the install script

**Comment by ruturajsambhusvt** [comment]
Hello, thanks for the quick response!

I tried this command `cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DOGRE_BUILD_COMPONENT_BITES=ON -DOGRE_BUILD_DEPENDENCIES=OFF -DOGRE_BUILD_SAMPLES=False -DOGRE_BUILD_COMPONENT_JAVA=OFF`

I think there is a typo in the install script.

Looks like it worked, I could run the examples! Thank you very much!

**Comment by jhwangbo** [comment]
Whats the typo?

**Comment by ruturajsambhusvt** [comment]
> Whats the typo?

Sorry for not being clear. The install Script has `OGRE_BUILD_COMPONENT_JAVA=OFF`.
What worked was -
`-DOGRE_BUILD_COMPONENT_JAVA=OFF`
