### ISSUE TITLE
Confused contact point in atlas

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimOgre#3]
Hi,

When I play with atlas example, I found very strange contact point inside knee and waist, which are not collided with ground or in self-collision.

I uploaded screenshots [here](https://docs.google.com/presentation/d/1CdnjAGD_6gum4rE4Wl0xo4if30VALb6ZPcYaBy_0N8E/edit?usp=sharing).

Thank you!
Fan

**Comment by jhwangbo** [comment]
that is a joint limit constraint, which is regarded as a collision.

**Comment by fanshi14** [comment]
I see, danke
