### ISSUE TITLE
Typo in cmake .. command for raisimOgre

### ISSUE THREAD

**Issue by basitimran37** [raisimTech/raisimOgre#30]
There is a typo in ogre cmake line:

What it is right now:
`$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DOGRE_BUILD_COMPONENT_BITES=ON -DOGRE_BUILD_DEPENDENCIES=OFF -DOGRE_BUILD_SAMPLES=False OGRE_BUILD_COMPONENT_JAVA=OFF`

Particularly, '-D' flag is missing in front of `OGRE_BUILD_COMPONENT_JAVA=OFF`.

**Comment by jhwangbo** [comment]
Thank you for the correction. I pushed a fix
