### ISSUE TITLE
Sensible default for activation key location

### ISSUE THREAD

**Issue by tomlankhorst** [raisimTech/raisimOgre#6]
Would it be possible to have a 'sensible default' for activation key location? 

Or even multiple search locations? 

e.g.:

- current working directory
- $HOME/.config/raisim/activation.raisim

**Comment by jhwangbo** [comment]
now it will search $HOME/.raisim/activation.raisim if no key path is provided. I updated it for Linux version for now. I'll soon update the windows and Mac version as well
