### ISSUE TITLE
Compilation error: Multiple definitions of `raisim::OgreVis::singletonPtr'

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimOgre#7]
When trying to compile my Raisim application I get the following error:

> /usr/bin/ld: CMakeFiles/gambol.dir/src/RaiSimViewer.cpp.o:(.bss+0x0): multiple definition of `raisim::OgreVis::singletonPtr'; CMakeFiles/gambol.dir/src/main.cpp.o:(.bss+0x0): first defined here
> collect2: error: ld returned 1 exit status

This happens when I try to use `OgreVis` through an intermediate class:

```
// main.h

#include "MyViewer.h"

int main() {
    MyViewer viewer();
}
```

```
// MyViewer.h

#ifndef SRC_RAISIMVIEWER_H_
#define SRC_RAISIMVIEWER_H_

#include <raisim/OgreVis.hpp>

class RaiSimViewer {

};

#endif //SRC_RAISIMVIEWER_H_
```

```
// MyViewer.cpp

#include "RaiSimViewer.h"

// Empty, no definitions yet
```

The kicker is: the program compiles when I comment out the `#include "RaiSimViewer.h"` in `MyViewer.cpp`.

Note that I can build and run the examples without any problems.  
I pulled, build and installed the latest versions of raisimLib and ogre.

And for completeness also make `CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.10.0)
project(Gambol VERSION 1.0.0 DESCRIPTION "Gait optimization platform")

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()

set(CMAKE_CXX_FLAGS "-Wall -Wextra")
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -Ofast")
set(CMAKE_CXX_STANDARD 14)

# Other packages
find_package(raisimOgre CONFIG REQUIRED)
find_package(Eigen3 REQUIRED NO_MODULE)

# Define output
add_executable(gambol src/main.cpp src/RaiSimViewer.cpp src/RaiSimViewer.h)

# Link libraries to output
target_link_libraries(gambol PUBLIC
        raisim::raisimOgre
        Eigen3::Eigen)
```

**Comment by jhwangbo** [comment]
I pushed a fix. Please pull and try it again.

**Comment by RobertoRoos** [comment]
Yes, that did the trick, thank you!
