### ISSUE TITLE
Map visualization segfaults with multiple threads

### ISSUE THREAD

**Issue by jelavice** [raisimTech/raisimOgre#8]
Hi Raisim Tech Team,

I am using raisim with ogre and I noticed that visualization of height map segfaults when the number of threads in the environment config file is more than 1. With a single thread the problem does not happen. The problem seems to be in OgreVis.cpp in "remove" function. Looks like the line 467 in OgreVis.cpp causes the problem. Looking at the line 466, it seems that the mesh is being removed if it hasn't been found in the map:
` primitiveMeshNames_.find(go.meshName) == primitiveMeshNames_.end()`

I was wondering whether that line should be changed to:
` primitiveMeshNames_.find(go.meshName) != primitiveMeshNames_.end()`

When I change the comparison sign from `==` to `!=` the problem does not happen anymore no matter what the number of threads.

Thank you for your help.

Best,

Edo

**Comment by jhwangbo** [comment]
thx for reporting. I pushed a fix

**Comment by jhwangbo** [comment]
Edo, this was a mistake. ``==`` is correct. We don't delete primitive meshes. That's why it checks if the deleted mesh is one of them.

changing to ``!=`` will simply skip the deletion of the graphical object. I reverted it to ``==``. I think your issue is somewhere else

**Comment by jelavice** [comment]
Thanks for letting me know and sorry for pushing a wrong "fix".

E
